name: Build main
on:
  push:
    branches:
      - main

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  IMAGE_GROUP: apicurio
  IMAGE_TAG: latest-snapshot

jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: github.repository_owner == 'apicurio'
    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      # Open-Source Machine emulator that allows you to emulate multiple CPU architectures on your machine
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare Build of Apicurio API Designer
        run: |
          cd "${{ github.workspace }}"

      - name: Build Apicurio API Designer
        run: |
          make pr-check

      - name: Set Image Tag
        run: echo "IMAGE_TAG=latest-snapshot" >> $GITHUB_ENV

        #      - name: Login to DockerHub Registry
        #        if: github.event_name == 'push'
        #        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Login to Quay.io Registry
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./dist/docker/target/docker
          file: ./dist/docker/target/docker/Dockerfile.jvm
          platforms: ${{env.PLATFORMS}}
          push: true
          tags: |
            quay.io/${{env.IMAGE_GROUP}}/apicurio-api-designer-mem:${{env.IMAGE_TAG}}
