name: Build PR

on:
  pull_request:
    branches:
      - main

env: { }

jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: github.repository_owner == 'apicurio'
    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      - name: Prepare Build of Apicurio API Designer
        run: |
          cd "${{ github.workspace }}"

      - name: Build Apicurio API Designer
        run: |
          make pr-check
