name: Build PR

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
      - 'CONTRIBUTING.md'
      - 'dco.txt'
    branches: [main]
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
      - 'CONTRIBUTING.md'
      - 'dco.txt'
    branches: [main]

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
  IMAGE_ORG: apicurio
  IMAGE_TAG: latest-snapshot

jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: github.repository_owner == 'apicurio'
    steps:
      - name: Checkout Code with Ref '${{ github.ref }}'
        uses: actions/checkout@v3

      # Set up the JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Set up node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Open-Source Machine emulator that allows you to emulate multiple CPU architectures on your machine
      - name: Set up QEMU
        if: github.event_name == 'push'
        uses: docker/setup-qemu-action@v1

      # Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        if: github.event_name == 'push'
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build Apicurio API Designer back-end
        run: mvn install -Dmaven.javadoc.skip=true --no-transfer-progress -DtrimStackTrace=false

      - name: Build Apicurio API Designer front-end
        run: |
          cd ui
          npm install
          npm run build
          npm run package

      - name: Login to Quay.io Registry
        if: github.event_name == 'push'
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Login to DockerHub Registry
        if: github.event_name == 'push'
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Publish Docker Image (Mem)
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: ./dist/docker/target/docker
          file: ./dist/docker/target/docker/Dockerfile.jvm
          platforms: ${{env.PLATFORMS}}
          push: true
          tags: |
            docker.io/${{env.IMAGE_ORG}}/apicurio-api-designer-mem:${{env.IMAGE_TAG}}
            quay.io/${{env.IMAGE_ORG}}/apicurio-api-designer-mem:${{env.IMAGE_TAG}}

      - name: Build and Publish Docker Image (SQL)
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: ./dist/docker/target/docker
          file: ./dist/docker/target/docker/Dockerfile.postgresql.jvm
          platforms: ${{env.PLATFORMS}}
          push: true
          tags: |
            docker.io/${{env.IMAGE_ORG}}/apicurio-api-designer-sql:${{env.IMAGE_TAG}}
            quay.io/${{env.IMAGE_ORG}}/apicurio-api-designer-sql:${{env.IMAGE_TAG}}

      - name: Build and Publish Docker Image (UI)
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: ./ui
          file: ./ui/Dockerfile
          platforms: ${{env.PLATFORMS}}
          push: true
          tags: |
            docker.io/${{env.IMAGE_ORG}}/apicurio-api-designer-ui:${{env.IMAGE_TAG}}
            quay.io/${{env.IMAGE_ORG}}/apicurio-api-designer-ui:${{env.IMAGE_TAG}}
